### ISSUE TITLE
Provide a .env sample file

### ISSUE THREAD

**Issue by nmiannay** [abdurshd/doston-law#1]
You should provide a sample (with fake values) `.env` file (e.g. `.env.example` ) in order to gather in one place all environment variables used over you project. It will help new joiners.
Also I suggest you to use a `config` object build with environment variables and validate it at boot time (you should have look at [this article](https://www.raulmelo.me/en/blog/best-practices-for-handling-per-environment-config-js-ts-applications/)).

**Comment by abdurshd** [comment]
Thanks for this. I added .env.example file to project.
Regarding the use of the config object, I read the article, but for now it does not seem much of relatable or problem in my project, because:
1. It might sound silly but project working well without that and I have to do a lot of not-working things before that.
2. If i got it right, in article author says in Next.js that kinda config comes out of box (I am using environment variables only back-end of the app, and i am not even using dotenv like we do in node.js): https://www.raulmelo.me/en/blog/best-practices-for-handling-per-environment-config-js-ts-applications/#:~:text=About%20.env%20files,task%20for%20you.
3. And he also says that it can be applicable in bunch of frameworks, but he did not mention Next.js: https://www.raulmelo.me/en/blog/best-practices-for-handling-per-environment-config-js-ts-applications/#:~:text=Still%2C%20the%20concept%20could%20be%20applied%20to%20any%20type%20of%20project%20that%20uses%20NodeJS%20as%20a%20development%20platform%2C%20such%20as%20Nuxt%2C%20Remix%2C%20Sveltekit%2C%20Express%2C%20Angular%2C%20etc.
